ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install -r requirements.txt &&
    python3 manage.py migrate
  command: >
    echo "from Blog.settings import *" > Blog/local_settings.py &&
    echo "ALLOWED_HOSTS = ['*']" >> Blog/local_settings.py &&
    export DJANGO_SETTINGS_MODULE=Blog.local_settings &&
    python3 manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true